
enable_audio_bell no

# special
foreground   #ffffff
background   #09243F
cursorColor  #ffffff

# black
color0       #000000
color8       #4d4d4d

# red
color1       #e22e32
color9       #fe2025

# green
color2       #5b043a
color10      #710749

# yellow
color3       #e0610a
color11      #e0610a

# blue
color4       #25aff4
color12      #0697e0

# magenta
color5       #db2572
color13      #ec106d

# cyan
color6       #a8ebfa
color14      #80e8ff

# white
color7       #e5e5e5
color15      #ffffff
