
enable_audio_bell no

foreground   #8567e6
background   #07001d
cursorColor  #8567e6

color0       #07001d
color8       #45396b

color1       #db2d20
color9       #f81c0c

color2       #eb3e79
color10      #ea1d63

color3       #af35c7
color11      #be14f1

color4       #3db9cd
color12      #2d8bd6

color5       #e51893
color13      #f401aa

color6       #8929d4
color14      #7515ec

color7       #dd2eb6
color15      #e11877
